# Generated by Django 5.2.7 on 2025-10-29 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unseen', max_length=200, verbose_name='Titre')),
                ('genre', models.CharField(choices=[('RPG', 'RPG'), ('FPS', 'FPS'), ('Metroidvania', 'Metroidvania'), ('Visual Novel', 'Visual Novel'), ('Platformer', 'Platformer'), ('Strategy', 'Strategy'), ('Adventure', 'Adventure'), ('Puzzle', 'Puzzle'), ('Dark Fantasy', 'Dark Fantasy')], max_length=50)),
                ('theme', models.TextField(blank=True, verbose_name='Thème')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='Mots-clés')),
                ('universe_description', models.TextField(blank=True, verbose_name="Description de l'univers")),
                ('story', models.TextField(blank=True, verbose_name='Histoire')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='concepts/covers/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_concepts', to=settings.AUTH_USER_MODEL)),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concept de jeu',
                'verbose_name_plural': 'Concepts de jeux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('role', models.CharField(max_length=100, verbose_name='Rôle')),
                ('description', models.TextField(verbose_name='Description')),
                ('game_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='studio.gameconcept')),
            ],
            options={
                'verbose_name': 'Personnage',
                'verbose_name_plural': 'Personnages',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('game_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='studio.gameconcept')),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
            },
        ),
    ]
