# Generated by Django 5.2.7 on 2025-10-29 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('RPG', 'RPG'), ('FPS', 'FPS'), ('Metroidvania', 'Metroidvania'), ('Visual Novel', 'Visual Novel')], max_length=50)),
                ('ambiance', models.CharField(max_length=150)),
                ('themes', models.TextField(help_text='Mots-clés thématiques')),
                ('references', models.TextField(blank=True, null=True)),
                ('universe', models.TextField(blank=True, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('characters', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
